# Generated by Django 4.0.5 on 2022-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenenergy',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AddField(
            model_name='greenenergy',
            name='consumed_energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='greenenergy',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='greenenergy',
            name='produced_energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='greenenergy',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
