# Generated by Django 4.0.5 on 2022-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_datetime_greenenergy_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenenergy',
            old_name='date',
            new_name='datetime',
        ),
    ]
