# Generated by Django 4.0.5 on 2022-10-22 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_greenenergy_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenenergy',
            name='datetime',
        ),
        migrations.AddField(
            model_name='greenenergy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='greenenergy',
            name='date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
