# Generated by Django 4.0.5 on 2022-10-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_greenenergy_datetime_greenenergy_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenenergy',
            name='date2',
        ),
    ]
