# Generated by Django 4.0.5 on 2022-10-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_greenenergy_date2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='greenEnergy',
            new_name='PhotovoltaicPanel',
        ),
    ]
