# Generated by Django 4.0.5 on 2022-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_photovoltaicpanel_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaicpanel',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaicpanel',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
